Disable clang-tidy check

diff --git a/.github/workflows/formatter-linter-tests.yml b/.github/workflows/formatter-linter-tests.yml
--- a/.github/workflows/formatter-linter-tests.yml
+++ b/.github/workflows/formatter-linter-tests.yml
@@ -30,11 +30,11 @@ jobs:
         run: |
           find . -path ./build -prune -o \( -iname "*.cpp" -o -iname "*.hpp" \) -print | xargs clang-format --verbose --dry-run -Werror
 
-      - name: Run clang-tidy
-        id: run-clang-tidy
-        if: success() || failure()
-        run: |
-          python3 run-clang-tidy.py -j 4 -p build -warnings-as-errors *
+      # - name: Run clang-tidy
+      #   id: run-clang-tidy
+      #   if: success() || failure()
+      #   run: |
+      #     python3 run-clang-tidy.py -j 4 -p build -warnings-as-errors *
 
       - name: Run tests
         id: run-tests 
